import { Document, Page, Text, View, StyleSheet } from "@react-pdf/renderer";
import type { Database } from "@/types/database";

type Settings = Database["public"]["Tables"]["business_settings"]["Row"];

export interface PriceListProduct {
  name: string;
  sub: string; // brand · size · type
  unit: string;
  base_paise: number;
  tiers: { min_quantity: number; price_paise: number }[];
}

const rupee = (paise: number) =>
  "Rs. " + (paise / 100).toLocaleString("en-IN", { minimumFractionDigits: 2, maximumFractionDigits: 2 });

const s = StyleSheet.create({
  page: { padding: 32, fontSize: 9, color: "#111", fontFamily: "Helvetica" },
  between: { flexDirection: "row", justifyContent: "space-between" },
  h1: { fontSize: 16, fontFamily: "Helvetica-Bold" },
  h2: { fontSize: 13, fontFamily: "Helvetica-Bold" },
  muted: { color: "#555" },
  bold: { fontFamily: "Helvetica-Bold" },
  headerBlock: { borderBottomWidth: 1, borderColor: "#ccc", paddingBottom: 8, marginBottom: 10 },
  row: {
    flexDirection: "row",
    justifyContent: "space-between",
    borderBottomWidth: 1,
    borderColor: "#eee",
    paddingVertical: 6,
  },
  left: { width: "55%", paddingRight: 8 },
  right: { width: "45%" },
  priceLine: { flexDirection: "row", justifyContent: "space-between", paddingVertical: 1 },
  footer: { marginTop: 24, textAlign: "center", color: "#888", fontSize: 8, borderTopWidth: 1, borderColor: "#eee", paddingTop: 8 },
});

export function PriceListPdf({
  business,
  products,
  date,
}: {
  business: Settings;
  products: PriceListProduct[];
  date: string;
}) {
  return (
    <Document title={`Price List - ${business.business_name}`}>
      <Page size="A4" style={s.page} wrap>
        <View style={[s.between, s.headerBlock]}>
          <View>
            <Text style={s.h1}>{business.business_name}</Text>
            {business.address ? <Text style={s.muted}>{business.address}</Text> : null}
            <Text style={s.muted}>
              {business.phone ? `Ph: ${business.phone}  ` : ""}
              {business.email ?? ""}
            </Text>
            {business.gstin ? <Text>GSTIN: {business.gstin}</Text> : null}
          </View>
          <View style={{ textAlign: "right" }}>
            <Text style={s.h2}>PRICE LIST</Text>
            <Text style={s.muted}>As on {date}</Text>
          </View>
        </View>

        {/* Column captions */}
        <View style={[s.between, { paddingBottom: 4 }]}>
          <Text style={[s.left, s.bold]}>Product</Text>
          <Text style={[s.right, s.bold, { textAlign: "right" }]}>Price (per piece)</Text>
        </View>

        {products.map((p, i) => (
          <View key={i} style={s.row} wrap={false}>
            <View style={s.left}>
              <Text style={s.bold}>{p.name}</Text>
              {p.sub ? <Text style={s.muted}>{p.sub}</Text> : null}
              <Text style={s.muted}>Unit: {p.unit}</Text>
            </View>
            <View style={s.right}>
              <View style={s.priceLine}>
                <Text style={s.muted}>1+ {p.unit}</Text>
                <Text style={s.bold}>{rupee(p.base_paise)}</Text>
              </View>
              {p.tiers.map((t, j) => (
                <View key={j} style={s.priceLine}>
                  <Text style={s.muted}>{t.min_quantity}+ {p.unit}</Text>
                  <Text>{rupee(t.price_paise)}</Text>
                </View>
              ))}
            </View>
          </View>
        ))}

        <Text style={s.footer}>
          Prices are per piece and subject to change. Generated by {business.business_name}.
        </Text>
      </Page>
    </Document>
  );
}
