import { Document, Page, Text, View, StyleSheet, Image } from "@react-pdf/renderer";
import type { Database } from "@/types/database";

type Settings = Database["public"]["Tables"]["business_settings"]["Row"];

export interface PriceRow {
  label: string; // e.g. "1–9", "20+"
  price_paise: number;
}
export interface PriceListProduct {
  name: string;
  sub: string; // brand · size · type
  unit: string;
  rows: PriceRow[];
}

const rupee = (paise: number) =>
  (paise / 100).toLocaleString("en-IN", { minimumFractionDigits: 2, maximumFractionDigits: 2 });

const s = StyleSheet.create({
  page: { padding: 30, fontSize: 9, color: "#1f2937", fontFamily: "Helvetica" },
  between: { flexDirection: "row", justifyContent: "space-between", alignItems: "flex-start" },
  h1: { fontSize: 17, fontFamily: "Helvetica-Bold", color: "#1F2D50" },
  h2: { fontSize: 13, fontFamily: "Helvetica-Bold", color: "#B5835A" },
  muted: { color: "#6b7280" },
  bold: { fontFamily: "Helvetica-Bold" },

  headerBlock: { borderBottomWidth: 2, borderColor: "#1F2D50", paddingBottom: 10, marginBottom: 14 },

  colHead: {
    flexDirection: "row",
    justifyContent: "space-between",
    backgroundColor: "#1F2D50",
    paddingVertical: 5,
    paddingHorizontal: 8,
    borderRadius: 3,
  },
  colHeadText: { fontFamily: "Helvetica-Bold", color: "#ffffff", fontSize: 8 },

  row: { flexDirection: "row", justifyContent: "space-between", paddingVertical: 7, paddingHorizontal: 8 },
  rowAlt: { backgroundColor: "#f9fafb" },

  left: { width: "52%", paddingRight: 8 },
  name: { fontFamily: "Helvetica-Bold", fontSize: 10, color: "#1F2D50" },
  sub: { color: "#6b7280", fontSize: 8, marginTop: 1 },

  priceBox: { width: 175 },
  priceLine: { flexDirection: "row", justifyContent: "space-between", paddingVertical: 1.5 },
  qtyText: { color: "#374151" },
  priceText: { fontFamily: "Helvetica-Bold", color: "#1F2D50" },
  rs: { color: "#6b7280", fontSize: 7 },

  footer: { marginTop: 22, textAlign: "center", color: "#9ca3af", fontSize: 8, borderTopWidth: 1, borderColor: "#e5e7eb", paddingTop: 8 },
});

export function PriceListPdf({
  business,
  products,
  date,
}: {
  business: Settings;
  products: PriceListProduct[];
  date: string;
}) {
  return (
    <Document title={`Price List - ${business.business_name}`}>
      <Page size="A4" style={s.page} wrap>
        {/* Letterhead */}
        <View style={[s.between, s.headerBlock]}>
          <View>
            {business.logo_url ? (
              <Image src={business.logo_url} style={{ height: 38, width: 100, objectFit: "contain", marginBottom: 5 }} />
            ) : null}
            <Text style={s.h1}>{business.business_name}</Text>
            {business.address ? <Text style={s.muted}>{business.address}</Text> : null}
            <Text style={s.muted}>
              {business.phone ? `Ph: ${business.phone}` : ""}
              {business.email ? `   ${business.email}` : ""}
            </Text>
            {business.gstin ? <Text style={s.muted}>GSTIN: {business.gstin}</Text> : null}
          </View>
          <View style={{ alignItems: "flex-end" }}>
            <Text style={s.h2}>PRICE LIST</Text>
            <Text style={s.muted}>As on {date}</Text>
          </View>
        </View>

        {/* Column headings */}
        <View style={s.colHead}>
          <Text style={[s.colHeadText, s.left]}>PRODUCT</Text>
          <View style={s.priceBox}>
            <View style={s.priceLine}>
              <Text style={s.colHeadText}>Qty (pcs)</Text>
              <Text style={s.colHeadText}>Price / piece</Text>
            </View>
          </View>
        </View>

        {/* Product rows */}
        {products.map((p, i) => (
          <View key={i} style={[s.row, i % 2 === 1 ? s.rowAlt : {}]} wrap={false}>
            <View style={s.left}>
              <Text style={s.name}>{p.name}</Text>
              {p.sub ? <Text style={s.sub}>{p.sub}</Text> : null}
            </View>
            <View style={s.priceBox}>
              {p.rows.map((r, j) => (
                <View key={j} style={s.priceLine}>
                  <Text style={s.qtyText}>{r.label}</Text>
                  <Text style={s.priceText}>
                    <Text style={s.rs}>Rs. </Text>
                    {rupee(r.price_paise)}
                  </Text>
                </View>
              ))}
            </View>
          </View>
        ))}

        <Text style={s.footer}>
          All prices are per piece and subject to change · Generated by {business.business_name} on {date}
        </Text>
      </Page>
    </Document>
  );
}
